import { test } from "node:test";
import assert from "node:assert/strict";
import { Router, ToolJsonCheck } from "../src/router.js";
import { modelTable, resolveModel, type Config, type Rung } from "../src/config.js";

const caps = (patch = {}) => ({ transport: "bedrock-runtime" as const, api: "converse" as const, toolUse: true, streaming: true, imageInput: false, structuredOutputs: true, promptCaching: false, contextWindow: 10000, maxOutput: 1000, ...patch });
const rr = (alias:string,vendor:string,serves:Rung["serves"],patch:Partial<Rung>={}):Rung=>({alias,vendor,serves,enabled:true,bedrockId:alias,inputPerM:1,outputPerM:2,capabilities:caps(),...patch});
const cfg:Config={stack:[rr("tiny","a",["trivial"]),rr("work-a","a",["execute"]),rr("work-b","b",["execute"]),rr("deep-b","b",["execute","explore"]),rr("deep-a","a",["explore"],{capabilities:caps({promptCaching:true,imageInput:true})})],routing:{enabled:true,keywords:{explore:["design"],execute:["implement"]},retryWindowMs:-1}};
const table=modelTable(cfg),model=(id:string)=>resolveModel(table,id)!;
const msg=(text:string,extra={})=>({model:"auto",messages:[{role:"user",content:text}],...extra});

test("routing uses the first eligible serving rung and preserves an incumbent vendor",()=>{const r=new Router(cfg);assert.equal(r.route(msg("implement it"),model("auto")).rung.alias,"work-a");const first=r.route(msg("design it"),model("auto"));assert.equal(first.rung.alias,"deep-b");const next=r.route({model:"auto",messages:[{role:"user",content:"design it"},{role:"assistant",content:"ok"},{role:"user",content:"implement"}]},model("auto"));assert.equal(next.rung.vendor,"b")});
test("capability filtering records skips and cache degradation",()=>{const r=new Router(cfg);const d=r.route(msg("implement",{tools:[{}],max_tokens:900}),model("auto"));assert.equal(d.rung.alias,"work-a");const image=r.route({model:"auto",messages:[{role:"user",content:[{type:"image_url",image_url:{url:"data:image/png;base64,eA=="}}]}]},model("auto"),"explore");assert.equal(image.rung.alias,"deep-a");assert.ok(image.skipped.some(x=>x.includes("no-image-input")));const cached=r.route(msg("design",{system:[{cachePoint:{type:"default"}}]}),model("auto"));assert.ok(cached.degraded.some(x=>x.includes("strip-cachePoint")))});
test("retry and observed failure walk right and raise class at the end",()=>{const r=new Router(cfg);const d=r.route(msg("implement"),model("auto"));assert.equal(r.observe(d,{errorStatus:429}).escalated,true);const n=r.route({model:"auto",messages:[{role:"user",content:"implement"},{role:"assistant",content:"x"},{role:"user",content:"continue"}]},model("auto"));assert.equal(n.rung.alias,"work-b")});
test("pinned cheap model bypasses routing and tool fragments validate",()=>{const r=new Router(cfg);assert.equal(r.route(msg("design"),model("tiny")).classReason,"client-model:pinned");const t=new ToolJsonCheck();t.add(0,'{"x":');t.add(0,"1}");assert.equal(t.malformed(),false);t.add(1,"{");assert.equal(t.malformed(),true)});
