import { createHash } from "node:crypto";
import type { Config, Rung } from "./config.js";
type Json = any;
export type Class = "trivial" | "execute" | "explore";
export type RoutingConfig = { enabled:boolean; honorClientModel:boolean; trivialBelowFloor:boolean; upgradeOnIntent:boolean; classifier:{enabled:boolean;model:string|null;mode:"fallback"|"always";maxChars:number;timeoutMs:number}; maxConversations:number;retryWindowMs:number;cacheHitRate:number;injectedMarkers:string[];shape:{exploreInputTokens:number;exploreTools:number;executeTurns:number;executeLastUserChars:number;trivialMaxChars:number;trivialMaxInputTokens:number;humanTurnMaxChars:number};keywords:Record<"execute"|"explore",string[]> };
export const ROUTING_DEFAULTS:RoutingConfig={enabled:false,honorClientModel:true,trivialBelowFloor:true,upgradeOnIntent:true,classifier:{enabled:false,model:null,mode:"fallback",maxChars:4000,timeoutMs:4000},maxConversations:1000,retryWindowMs:60000,cacheHitRate:.8,
 // ponytail: prefix match against a marker list, not a parser. U+2063 is firstmate's invisible machine prefix; add a
 // marker per harness. The size cap is the backstop for harnesses that inject without marking.
 injectedMarkers:["⁣"],shape:{exploreInputTokens:60000,exploreTools:40,executeTurns:8,executeLastUserChars:200,trivialMaxChars:300,trivialMaxInputTokens:1500,humanTurnMaxChars:4000},keywords:{explore:[],execute:[]}};
export type Decision={rung:Rung;undecided:boolean;class:Class|null;classReason:string;conversationKey:string|null;sticky:boolean;escalated:boolean;escalationReason:string|null;eligibleCount:number;skipped:string[];degraded:string[]};
export type Outcome={stopReason?:string|null;outputTokens?:number|null;errorStatus?:number|null;aborted?:boolean;malformedToolJson?:boolean};
type Entry={class:Class;alias:string;vendor:string;lastSeen:number;lastPrompt:string};
const text=(c:Json):string=>typeof c==="string"?c:Array.isArray(c)?c.map(p=>p?.type==="text"?p.text??"":"").join(""):"";
const strip=(s:string)=>s.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g,"");
/** A harness speaking to the model in the user's name: a session digest, a watcher wake, an agent nudge. Never the human. */
export const injected=(t:string,rc:Pick<RoutingConfig,"injectedMarkers"|"shape">)=>!t||t.length>rc.shape.humanTurnMaxChars||rc.injectedMarkers.some(m=>m&&t.startsWith(m));
export function promptShape(body:Json,rc:Pick<RoutingConfig,"injectedMarkers"|"shape">=ROUTING_DEFAULTS){const ms:Json[]=Array.isArray(body.messages)?body.messages:[];const sys=ms.filter(m=>m.role==="system"||m.role==="developer");
 // Classification must read what the human typed. An injected 17KB digest mentioning "architecture" once must not make a
 // "hi" session an explore session, so injected turns are dropped before any signal looks at the text.
 const users=ms.filter(m=>m.role==="user").map(m=>strip(text(m.content)).trim()).filter(t=>!injected(t,rc));
 return{system:[text(body.system),...sys.map(m=>text(m.content))].join("\n"),firstUser:users[0]??"",lastUser:users.at(-1)??"",turns:ms.length,dialogTurns:ms.length-sys.length,tools:Array.isArray(body.tools)?body.tools.length:0,inputTokens:Math.ceil(JSON.stringify(body).length/4),thinking:body.thinking?.type==="enabled"||/^(high|xhigh|max)$/.test(String(body.reasoning_effort??"")),userId:body.metadata?.user_id??body.user??""}}
const words=(xs:string[])=>xs.length?new RegExp(`\\b(${xs.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|")})\\b`,"i"):/$^/;
const hash=(s:string)=>createHash("sha256").update(s).digest("hex");
const rank:Record<Class,number>={trivial:0,execute:1,explore:2};
const userTurn=(body:Json,rc:Pick<RoutingConfig,"injectedMarkers"|"shape">)=>{const ms=Array.isArray(body.messages)?body.messages:[],m=ms.at(-1);if(!m||m.role!=="user")return false;if(Array.isArray(m.content)&&(!m.content.some((p:Json)=>p?.type==="text")||m.content.some((p:Json)=>p?.type==="tool_result")))return false;return!injected(strip(text(m.content)).trim(),rc)};
/** What a million input tokens really cost on this rung, once prompt caching is priced in. A cache read bills at a tenth. */
export const effectiveInputPerM=(r:Rung,hitRate:number)=>r.capabilities.promptCaching?r.inputPerM*(1-.9*Math.min(Math.max(hitRate,0),1)):r.inputPerM;
const contains=(v:Json,key:string):boolean=>!!v&&typeof v==="object"&&(Object.hasOwn(v,key)||Object.values(v).some(x=>contains(x,key)));

export class Router{
 readonly rc:RoutingConfig;private explore:RegExp;private execute:RegExp;private conv=new Map<string,Entry>();
 /** Rungs this account cannot invoke, learned from Bedrock at request time. Per process: a restart re-learns, so a new entitlement needs no config edit. */
 readonly unavailable=new Set<string>();
 constructor(private cfg:Config){const r=cfg.routing??{};this.rc={...ROUTING_DEFAULTS,...r,shape:{...ROUTING_DEFAULTS.shape,...r.shape},keywords:{...ROUTING_DEFAULTS.keywords,...r.keywords},classifier:{...ROUTING_DEFAULTS.classifier,...r.classifier}};if(this.rc.classifier.enabled&&!this.rc.classifier.model)throw new Error("routing.classifier.model is required when the classifier is enabled");this.explore=words(this.rc.keywords.explore);this.execute=words(this.rc.keywords.execute);
  // Cheapest-first by *effective* input price: for agentic traffic the prompt is re-sent every turn, so a caching rung at a
  // higher list price often beats a cheaper one without it. Ties keep the configured order, which stays the tiebreak.
  this.ranked=cfg.stack.map((r,i)=>({r,i})).sort((a,b)=>effectiveInputPerM(a.r,this.rc.cacheHitRate)-effectiveInputPerM(b.r,this.rc.cacheHitRate)||a.i-b.i).map(x=>x.r)}
 /** The stack in selection order. Everything that compares rung positions must use this, never cfg.stack. */
 readonly ranked:Rung[];
 classify(body:Json,s=promptShape(body),allowTrivial=this.cfg.stack.some(r=>r.enabled&&r.serves.includes("trivial"))){const x=this.rc.shape;if(s.thinking)return{class:"explore" as Class,reason:"thinking"};if(s.inputTokens>=x.exploreInputTokens)return{class:"explore" as Class,reason:"shape:long-context"};if(s.tools>=x.exploreTools)return{class:"explore" as Class,reason:"shape:many-tools"};if(s.turns>=x.executeTurns&&s.lastUser.length<=x.executeLastUserChars)return{class:"execute" as Class,reason:"shape:agentic-loop"};if(this.explore.test(s.lastUser))return{class:"explore" as Class,reason:"keyword:explore"};if(this.execute.test(s.lastUser))return{class:"execute" as Class,reason:"keyword:execute"};if(allowTrivial&&s.dialogTurns<=1&&!s.tools&&s.lastUser.length>0&&s.lastUser.length<=x.trivialMaxChars&&s.inputTokens<=x.trivialMaxInputTokens)return{class:"trivial" as Class,reason:"shape:trivial"};return{class:"execute" as Class,reason:"default"}}
 /** The output cap the client asked for. Mirrors translate.ts: OpenAI's newer field wins, so both shapes are seen. */
 static maxTokens(body:Json){return Number(body.max_completion_tokens??body.max_tokens??0)}
 /** The client's output cap is a ceiling, not a requirement, so it never filters a rung: it only clamps what is sent. */
 eligible(body:Json,cls:Class,excluded=new Set<string>()){const s=promptShape(body,this.rc),skipped:string[]=[],degraded:string[]=[];const want=Router.maxTokens(body);const image=contains(body.messages,"image")||JSON.stringify(body.messages??[]).includes('"image_url"'),schema=body.response_format?.type==="json_schema"||!!body.response_format?.json_schema,cache=contains(body,"cachePoint");const rungs=this.ranked.filter(r=>{const why=!r.enabled?"disabled":this.unavailable.has(r.alias)?"unavailable":excluded.has(r.alias)?"request-ineligible":!r.serves.includes(cls)?`does-not-serve:${cls}`:s.tools&&!r.capabilities.toolUse?"no-tool-use":image&&!r.capabilities.imageInput?"no-image-input":body.stream&&!r.capabilities.streaming?"no-streaming":schema&&!r.capabilities.structuredOutputs?"no-structured-outputs":s.inputTokens>r.capabilities.contextWindow?"context-window":"";if(why){skipped.push(`${r.alias}:${why}`);return false}if(cache&&!r.capabilities.promptCaching)degraded.push(`${r.alias}:strip-cachePoint`);if(want>r.capabilities.maxOutput)degraded.push(`${r.alias}:clamp-maxTokens:${r.capabilities.maxOutput}`);return true});return{rungs,skipped,degraded}}
 route(body:Json,requested:Rung,header?:string,excluded=new Set<string>()):Decision{const off=(reason:string):Decision=>({rung:requested,undecided:false,class:null,classReason:reason,conversationKey:null,sticky:false,escalated:false,escalationReason:null,eligibleCount:1,skipped:[],degraded:[]});if(!this.rc.enabled)return off("disabled");if(header==="off")return off("header:off");const s=promptShape(body,this.rc),key=hash(s.userId+"\0"+s.system+"\0"+s.firstUser).slice(0,16),prompt=hash(JSON.stringify(body.messages??null)),now=Date.now();let entry=this.conv.get(key),reason="sticky",escalated=false,escalationReason:string|null=null;if(entry&&entry.class==="trivial"&&this.classify(body,s).class!=="trivial")entry=undefined;if(!entry){const c=this.classify(body,s);entry={class:c.class,alias:"",vendor:"",lastSeen:now,lastPrompt:""};reason=c.reason}else if(entry.alias&&entry.lastPrompt===prompt&&now-entry.lastSeen<=this.rc.retryWindowMs){escalationReason="retry";escalated=this.bump(entry,body,excluded)}else if(userTurn(body,this.rc)){const c=this.classify(body,s);
  // Each human turn is a fresh chance to be right. Raising needs a strong signal so a conversation does not thrash upward;
  // lowering needs none, because a class that sticks forever turns one bad guess into every later request's price.
  if(this.rc.upgradeOnIntent&&rank[c.class]>rank[entry.class]&&/^(thinking|keyword:explore)$/.test(c.reason)){entry.class=c.class;entry.alias="";reason=`upgrade:${c.reason}`}
  else if(rank[c.class]<rank[entry.class]){entry.class=c.class;entry.alias="";reason=`downgrade:${c.reason}`}}
 let cls=entry.class;if(header==="trivial"||header==="execute"||header==="explore"){cls=header;reason=`header:${header}`}let pool=this.eligible(body,cls,excluded);
 // A class whose rungs are all unreachable degrades to the next class down instead of failing the request: a weaker
 // answer beats none. Emptiness from a capability filter is unaffected, since the same filter applies to every class.
 for(const lower of ["execute","trivial"] as Class[]){if(pool.rungs.length||rank[lower]>=rank[cls])continue;const p=this.eligible(body,lower,excluded);if(p.rungs.length){pool={...p,skipped:[...pool.skipped,...p.skipped]};cls=lower;reason=`degrade:${lower}`}}
 const candidates=pool.rungs;if(!candidates.length)throw new Error(`no enabled rung is eligible for ${cls}: ${pool.skipped.join(", ")}`);let chosen=candidates.find(r=>r.alias===entry!.alias)??(entry.vendor?candidates.find(r=>r.vendor===entry!.vendor):undefined)??candidates[0];const reqAt=this.ranked.findIndex(r=>r.alias===requested.alias),chosenAt=this.ranked.findIndex(r=>r.alias===chosen.alias),executeAt=this.ranked.findIndex(r=>r.enabled&&r.serves.includes("execute"));if(!requested.auto&&reqAt>=0&&reqAt<executeAt)return{...off("client-model:pinned"),class:"execute"};if(!requested.auto&&this.rc.honorClientModel&&!(cls==="trivial"&&this.rc.trivialBelowFloor)&&chosenAt<reqAt)chosen=candidates.find(r=>this.ranked.indexOf(r)>=reqAt)??chosen;if(!reason.startsWith("header:")){entry.class=cls;entry.alias=chosen.alias;entry.vendor=chosen.vendor;this.touch(key,entry,now,prompt)}const soft=/^(default|keyword:.*|shape:trivial)$/.test(reason);return{rung:chosen,undecided:soft&&(this.rc.classifier.mode==="always"||reason==="default"),class:cls,classReason:reason,conversationKey:key,sticky:reason==="sticky",escalated,escalationReason,eligibleCount:candidates.length,skipped:pool.skipped,degraded:pool.degraded.filter(x=>x.startsWith(chosen.alias+":"))}}
 /** A turn that carries tools can be asked to call one, whatever it looks like: "hi" to an agentic harness runs its startup
  * checks. The shape rules already refuse trivial when tools are present; the classifier's verdict is held to the same floor. */
 private floor(c:Class,body:Json):Class{return c==="trivial"&&(Array.isArray(body.tools)?body.tools.length:0)>0?"execute":c}
 reclassify(d:Decision,requested:Rung,verdict:Class,reason:string,body:Json={}):Decision{if(!d.conversationKey)return d;const v=this.floor(verdict,body);const e=this.conv.get(d.conversationKey);if(e){e.class=v;e.alias=""}const n=this.route(body,requested,v);return{...n,conversationKey:d.conversationKey,classReason:v===verdict?reason:`${reason}+tools-floor`,undecided:false}}
 observe(d:Decision,o:Outcome,body:Json={}){const none={escalated:false,reason:null as string|null};if(!d.conversationKey||o.aborted)return none;const e=this.conv.get(d.conversationKey);if(!e)return none;const reason=o.errorStatus===429||(o.errorStatus??0)>=500?`bedrock:${o.errorStatus}`:o.stopReason==="max_tokens"?"max_tokens":o.malformedToolJson?"malformed-tool-json":o.outputTokens===0?"empty":null;return reason?{escalated:this.bump(e,body,new Set()),reason}:none}
 /** Learn that this account cannot invoke a rung. Any conversation stuck to it loses its sticky choice, so the next route() reselects. */
 markUnavailable(alias:string){this.unavailable.add(alias);for(const e of this.conv.values())if(e.alias===alias)e.alias=""}
 invalidate(d:Decision,body:Json){if(!d.conversationKey)return false;const e=this.conv.get(d.conversationKey);return e?this.bump(e,body,new Set([d.rung.alias])):false}
 private bump(e:Entry,body:Json,excluded:Set<string>){const at=this.ranked.findIndex(r=>r.alias===e.alias);let next=this.eligible(body,e.class,excluded).rungs.find(r=>this.ranked.indexOf(r)>at);if(!next&&e.class!=="explore"){e.class=e.class==="trivial"?"execute":"explore";next=this.eligible(body,e.class,excluded).rungs.find(r=>this.ranked.indexOf(r)>at)}if(!next)return false;e.alias=next.alias;e.vendor=next.vendor;return true}
 private touch(k:string,e:Entry,n:number,p:string){e.lastSeen=n;e.lastPrompt=p;this.conv.delete(k);this.conv.set(k,e);if(this.conv.size>this.rc.maxConversations)this.conv.delete(this.conv.keys().next().value!)}
}
export class ToolJsonCheck{private parts=new Map<number,string>();add(i:number,f:string){this.parts.set(i,(this.parts.get(i)??"")+f)}malformed(){for(const s of this.parts.values())try{JSON.parse(s||"{}")}catch{return true}return false}}
